### ISSUE TITLE
I want to get the return value of "function _linear(data, decimalPlaces)" in "example1-addSeries.html",how to do it?

### ISSUE THREAD

**Issue by dapsjj** [streamlinesocial/highcharts-regression#70] opened 2018-04-27 06:46 UTC
I want to get the return value of "function _linear(data, decimalPlaces)" in "example1-addSeries.html",how to do it?

**Comment by phpepe** [comment] 2020-03-09 15:41
Duplicate of #54

**Closed** 2020-03-09 15:41 UTC
